### PR TITLE
Adding filtering for every-class methods to the What's New tool

### PR DESCRIPTION
**Pull request by AlexJerabek**

### CODE REVIEW

**Comment by o365devx** [comment]
Docs Build status updates of commit _[b99b869](https://github.com/OfficeDev/office-js-docs-reference/pull/414/commits/b99b86932c1428b1705ddf81910f45aeec57c29c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[generate-docs/package-lock.json](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-WNTool/generate-docs/package-lock.json) | :white_check_mark:Succeeded | |
[generate-docs/scripts/package-lock.json](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-WNTool/generate-docs/scripts/package-lock.json) | :white_check_mark:Succeeded | |
[generate-docs/tools/WhatsNew.ts](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-WNTool/generate-docs/tools/WhatsNew.ts) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C6%5C3%5C0e1871f2-88cb-c16b-6d81-dc80e4f66cef%5CPullRequest%5C201906032126073216-414%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=PPvw5tRvDE%2Bu7QyUdeeweCi39SgFJi51A7yQ%2BDtrr%2F0%3D&st=2019-06-03T21%3A27%3A59Z&se=2019-07-04T21%3A32%3A59Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by ElizabethSamuel-MSFT** [comment]
@AlexJerabek Do we need these package-lock changes?

**Comment by o365devx** [comment]
Docs Build status updates of commit _[49b12a3](https://github.com/OfficeDev/office-js-docs-reference/pull/414/commits/49b12a3ed82f715fdf28abaa02d16bbbe10af774)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[generate-docs/package-lock.json](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-WNTool/generate-docs/package-lock.json) | :white_check_mark:Succeeded | |
[generate-docs/scripts/package-lock.json](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-WNTool/generate-docs/scripts/package-lock.json) | :white_check_mark:Succeeded | |
[generate-docs/tools/WhatsNew.ts](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-WNTool/generate-docs/tools/WhatsNew.ts) | :white_check_mark:Succeeded | |
[generate-docs/tools/package-lock.json](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-WNTool/generate-docs/tools/package-lock.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C6%5C3%5C0e1871f2-88cb-c16b-6d81-dc80e4f66cef%5CPullRequest%5C201906032201583681-414%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1D3EM9QTVVCVZ9GApJ7y8kZ6qOgBTFnPmfxgfMpjRU8%3D&st=2019-06-03T22%3A03%3A10Z&se=2019-07-04T22%3A08%3A10Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[7ea87bb](https://github.com/OfficeDev/office-js-docs-reference/pull/414/commits/7ea87bbb8ce07124e90e9e0eb6785f6e5b1e15bf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[generate-docs/tools/WhatsNew.ts](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-WNTool/generate-docs/tools/WhatsNew.ts) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C6%5C3%5C0e1871f2-88cb-c16b-6d81-dc80e4f66cef%5CPullRequest%5C201906032203423802-414%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ctiPgfLLRZ3ZLCtAKtZsT%2FFl70FLTrVBTE76pTUOaZ8%3D&st=2019-06-03T22%3A09%3A27Z&se=2019-07-04T22%3A14%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
