### PR TITLE
Merge to live

### PR DESCRIPTION
**Pull request by AlexJerabek**

### CODE REVIEW

**Comment by AlexJerabek** [comment]
@davidchesnut and @Rick-Kirkham, 
When these API updates go live, will we be ready to publish the corresponding docs in office-js-docs-pr?

**Comment by o365devx** [comment]
Docs Build status updates of commit _[6dbacf6](https://github.com/OfficeDev/office-js-docs-reference/commits/6dbacf651772bc4860d2aaf33afe9c2e2f1b3289)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/docs-ref-autogen/common/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/common/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/excel/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_1/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/excel_1_1/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_10/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/excel_1_10/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_2/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/excel_1_2/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_3/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/excel_1_3/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_4/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/excel_1_4/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_5/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/excel_1_5/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_6/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/excel_1_6/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_7/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/excel_1_7/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_8/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/excel_1_8/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_9/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/excel_1_9/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_online/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/excel_online/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/office/office.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/office/office.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/office/office/office.addin.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/office/office/office.addin.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/office/office/office.control.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/office/office/office.control.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/office/office/office.gallery.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/office/office/office.gallery.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/office/office/office.ribbon.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/office/office/office.ribbon.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/office/office/office.ribbonupdaterdata.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/office/office/office.ribbonupdaterdata.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/office/office/office.startupbehavior.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/office/office/office.startupbehavior.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/office/office/office.tab.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/office/office/office.tab.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/office/office/office.visibilitymode.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/office/office/office.visibilitymode.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/office/office/office.visibilitymodechangedmessage.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/office/office/office.visibilitymodechangedmessage.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/onenote/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/onenote/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/outlook/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_1/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/outlook_1_1/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_2/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/outlook_1_2/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_3/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/outlook_1_3/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_4/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/outlook_1_4/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_5/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/outlook_1_5/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_6/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/outlook_1_6/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_7/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/outlook_1_7/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_8/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/outlook_1_8/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/powerpoint/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/powerpoint/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/visio/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/visio/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/word/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/word/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/word_1_1/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/word_1_1/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/word_1_2/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/word_1_2/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/word_1_3/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/word_1_3/toc.yml) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-office/office.d.ts](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-office/office.d.ts) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-outlook/outlook.d.ts](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-outlook/outlook.d.ts) | :white_check_mark:Succeeded | |
[generate-docs/json/office/office.api.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/json/office/office.api.json) | :white_check_mark:Succeeded | |
[generate-docs/script-inputs/office_preview.d.ts](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/script-inputs/office_preview.d.ts) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C2%5C20%5C0e1871f2-88cb-c16b-6d81-dc80e4f66cef%5CPullRequest%5C202002202224298510-635%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KmO%2BHgJkpl1i5mIbN2RsOQwUoNI9sk17u%2FMAeiCdaSk%3D&st=2020-02-20T22%3A47%3A19Z&se=2020-03-22T22%3A52%3A19Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Rick-Kirkham** [comment]
> @davidchesnut and @Rick-Kirkham,
> When these API updates go live, will we be ready to publish the corresponding docs in office-js-docs-pr?

@AlexJerabek The ShareRuntime Req Set article and the showAsTaskpane conceptual article are ready. Last I heard, Jeremy was aiming for all of this stuff to publish on Mar. 2nd. But I don't think its a big deal if the ref content appears earlier than that.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[c5f8a06](https://github.com/OfficeDev/office-js-docs-reference/commits/c5f8a06a19a54a20e6e01df2b3785b3b394f74c0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/docs-ref-autogen/common/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/common/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/excel/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_1/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/excel_1_1/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_10/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/excel_1_10/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_2/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/excel_1_2/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_3/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/excel_1_3/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_4/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/excel_1_4/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_5/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/excel_1_5/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_6/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/excel_1_6/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_7/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/excel_1_7/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_8/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/excel_1_8/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_9/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/excel_1_9/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_online/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/excel_online/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/office/office.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/office/office.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/office/office/office.addin.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/office/office/office.addin.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/office/office/office.control.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/office/office/office.control.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/office/office/office.gallery.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/office/office/office.gallery.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/office/office/office.ribbon.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/office/office/office.ribbon.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/office/office/office.ribbonupdaterdata.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/office/office/office.ribbonupdaterdata.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/office/office/office.startupbehavior.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/office/office/office.startupbehavior.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/office/office/office.tab.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/office/office/office.tab.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/office/office/office.visibilitymode.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/office/office/office.visibilitymode.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/office/office/office.visibilitymodechangedmessage.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/office/office/office.visibilitymodechangedmessage.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/onenote/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/onenote/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook/outlook/office.appointmentread.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/outlook/outlook/office.appointmentread.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook/outlook/office.attachmentdetails.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/outlook/outlook/office.attachmentdetails.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook/outlook/office.mailbox.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/outlook/outlook/office.mailbox.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook/outlook/office.messageread.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/outlook/outlook/office.messageread.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/outlook/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_1/outlook/office.appointmentread.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/outlook_1_1/outlook/office.appointmentread.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_1/outlook/office.attachmentdetails.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/outlook_1_1/outlook/office.attachmentdetails.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_1/outlook/office.mailbox.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/outlook_1_1/outlook/office.mailbox.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_1/outlook/office.messageread.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/outlook_1_1/outlook/office.messageread.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_1/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/outlook_1_1/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_2/outlook/office.appointmentread.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/outlook_1_2/outlook/office.appointmentread.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_2/outlook/office.attachmentdetails.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/outlook_1_2/outlook/office.attachmentdetails.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_2/outlook/office.mailbox.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/outlook_1_2/outlook/office.mailbox.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_2/outlook/office.messageread.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/outlook_1_2/outlook/office.messageread.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_2/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/outlook_1_2/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_3/outlook/office.appointmentread.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/outlook_1_3/outlook/office.appointmentread.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_3/outlook/office.attachmentdetails.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/outlook_1_3/outlook/office.attachmentdetails.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_3/outlook/office.mailbox.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/outlook_1_3/outlook/office.mailbox.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_3/outlook/office.messageread.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/outlook_1_3/outlook/office.messageread.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_3/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/outlook_1_3/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_4/outlook/office.appointmentread.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/outlook_1_4/outlook/office.appointmentread.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_4/outlook/office.attachmentdetails.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/outlook_1_4/outlook/office.attachmentdetails.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_4/outlook/office.mailbox.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/outlook_1_4/outlook/office.mailbox.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_4/outlook/office.messageread.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/outlook_1_4/outlook/office.messageread.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_4/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/outlook_1_4/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_5/outlook/office.appointmentread.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/outlook_1_5/outlook/office.appointmentread.yml) | :white_check_mark:Succeeded | |

This comment lists only the first 50 files in the pull request.
For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C2%5C21%5C0e1871f2-88cb-c16b-6d81-dc80e4f66cef%5CPullRequest%5C202002211744295779-635%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=w%2FruZ7V5IMgcqn4VlcgHZtB77gqQVVtYGJ%2FvzaAZvps%3D&st=2020-02-21T18%3A07%3A24Z&se=2020-03-23T18%3A12%3A24Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
