### PR TITLE
Document ActiveViewChanged works in PowerPoint only

### PR DESCRIPTION
**Pull request by jozefizso**

### CODE REVIEW

**Comment by AlexJerabek** [comment]
Hi @jozefizso,

Thanks for submitting this PR. Most of the files in this repo are automatically generated. I'll tag @Rick-Kirkham to verify the proposed changes and get them checked into the upstream [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repo.

**Comment by Rick-Kirkham** [comment]
@jozefizso Thanks. The files in this repo are actually autogenerated from another source, so they can't be updated directly with a PR. I will confirm your information with the platform team and update the actual source file. It will be a few days at least before you see the change. In the meantime, I'll close this PR.

**Comment by Rick-Kirkham** [comment]
@jozefizso It looks like this information is documented in the [getActiveReviewAsync](https://docs.microsoft.com/en-us/javascript/api/office/office.document?view=common-js-preview#office-office-document-getactiveviewasync-member(1)) method which is the best place for it. So, I think the only change to the enum value description is to specify that it only applies to PowerPoint.

**Comment by jozefizso** [comment]
@Rick-Kirkham thanks for directing me to definitely typed repo!

**Pull request closed without merging**
