### PR TITLE
Updating tooling notes and shifting snippet parsing to midprocessor

### PR DESCRIPTION
**Pull request by AlexJerabek**
This PR makes the midprocessor solely responsible for working with snippets (as they're only needed for the API Documentor). It also adjusts the tooling pipeline notes and updates the picture.

ToolingPipeline

### CODE REVIEW

**Comment by o365devx** [comment]
Docs Build status updates of commit _[3da4315](https://github.com/OfficeDev/office-js-docs-reference/commits/3da4315cad5fc777a5e3d22c474d8e2080cb995a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[DocumentationToolingNotes.md](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-MidSnips/DocumentationToolingNotes.md) | :white_check_mark:Succeeded | |
[ToolingPipeline.png](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-MidSnips/ToolingPipeline.png) | :white_check_mark:Succeeded | |
[ToolingPipeline.vsdx](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-MidSnips/ToolingPipeline.vsdx) | :white_check_mark:Succeeded | |
[generate-docs/scripts/midprocessor.ts](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-MidSnips/generate-docs/scripts/midprocessor.ts) | :white_check_mark:Succeeded | |
[generate-docs/scripts/preprocessor.ts](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-MidSnips/generate-docs/scripts/preprocessor.ts) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C1%5C3%5C0e1871f2-88cb-c16b-6d81-dc80e4f66cef%5CPullRequest%5C202001032214321538-592%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jSkS9b81fli7wbzXvi3VJTr%2BdPpa3X9r2O%2Fn4rhv4pc%3D&st=2020-01-03T22%3A35%3A59Z&se=2020-02-03T22%3A40%3A59Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by AlexJerabek** [comment]
@mscharlock Good catch. The CF-related type definitions are still part of the process. Updated the diagram.
ToolingPipeline

**Comment by o365devx** [comment]
Docs Build status updates of commit _[6d0e915](https://github.com/OfficeDev/office-js-docs-reference/commits/6d0e9152da3b1e99ff71f54ac7b41b514581c1e3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[DocumentationToolingNotes.md](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-MidSnips/DocumentationToolingNotes.md) | :white_check_mark:Succeeded | |
[ToolingPipeline.png](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-MidSnips/ToolingPipeline.png) | :white_check_mark:Succeeded | |
[ToolingPipeline.vsdx](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-MidSnips/ToolingPipeline.vsdx) | :white_check_mark:Succeeded | |
[generate-docs/scripts/midprocessor.ts](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-MidSnips/generate-docs/scripts/midprocessor.ts) | :white_check_mark:Succeeded | |
[generate-docs/scripts/preprocessor.ts](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-MidSnips/generate-docs/scripts/preprocessor.ts) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C1%5C6%5C0e1871f2-88cb-c16b-6d81-dc80e4f66cef%5CPullRequest%5C202001061813209570-592%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=BIcnGQ1679r8xV%2FCA0Z0ceq%2BY9fZUTsPUcHl%2Bv%2F8iuE%3D&st=2020-01-06T18%3A37%3A02Z&se=2020-02-06T18%3A42%3A02Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[70c4ef3](https://github.com/OfficeDev/office-js-docs-reference/commits/70c4ef319bf9c7a8a462e62aa2e7af1c06c9bef0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[DocumentationToolingNotes.md](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-MidSnips/DocumentationToolingNotes.md) | :white_check_mark:Succeeded | |
[ToolingPipeline.png](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-MidSnips/ToolingPipeline.png) | :white_check_mark:Succeeded | |
[ToolingPipeline.vsdx](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-MidSnips/ToolingPipeline.vsdx) | :white_check_mark:Succeeded | |
[generate-docs/scripts/midprocessor.ts](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-MidSnips/generate-docs/scripts/midprocessor.ts) | :white_check_mark:Succeeded | |
[generate-docs/scripts/preprocessor.ts](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-MidSnips/generate-docs/scripts/preprocessor.ts) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C1%5C6%5C0e1871f2-88cb-c16b-6d81-dc80e4f66cef%5CPullRequest%5C202001061814502112-592%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=pJuJJnaHxASOyD4X7XDih1laYGuGN43lXsDYOgGACAk%3D&st=2020-01-06T19%3A03%3A23Z&se=2020-02-06T19%3A08%3A23Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
