### PR TITLE
[Admin] (docs metadata) Update metadata attribute values for docs.

### PR DESCRIPTION
**Pull request by kbrandl**
This PR updates metadata attribute values to improve our ability to generate reports about this doc set. It does the following: 
- sets ms.suite metadata attribute (by using **globalMetadata** config setting in **docfx.json**)
- removes the default value for metadata attribute **ms.prod** (i.e., deletes corresponding **globalMetadata** config setting in **docfx.json**)
- sets metadata attribute **ms.prod** to the appropriate value for all files (by using **fileMetadata** config setting in **docfx.json**)

### CODE REVIEW

**Comment by o365devx** [comment]
OPS Build status updates of commit _[491383c](https://github.com/OfficeDev/office-js-docs-reference/pull/313/commits/491383c9b9d51979dc558162824b057dc74c7e21)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 2 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[491383c](https://github.com/OfficeDev/office-js-docs-reference/pull/313/commits/491383c9b9d51979dc558162824b057dc74c7e21)_: 

:clock10: **Full build**: average full build time is _3 min(s) 54 sec(s)_ [calculated from last _6_ build(s)]

> Note: A full build takes more time than an incremental build.  This is the expected behavior of the build system.

**Comment by o365devx** [comment]
OPS Build status updates of commit _[491383c](https://github.com/OfficeDev/office-js-docs-reference/pull/313/commits/491383c9b9d51979dc558162824b057dc74c7e21)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/docfx.json](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-update-metadata-attributes/docs/docfx.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C7%5C0e1871f2-88cb-c16b-6d81-dc80e4f66cef%5CPullRequest%5C201902072108127602-313%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=VJvl5IamI%2BHWKGnuOyjRD0ei%2FS8ZZ8n4dgbVTD0IJkY%3D&st=2019-02-07T21%3A06%3A49Z&se=2019-03-10T21%3A11%3A49Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kbrandl** [comment]
@lindalu-MSFT the APEX team recently whitelisted the following combinations of **ms.prod** and **ms.technology** attribute values for the Add-ins docs, so this PR updates the values of those attributes in OfficeDev/office-js-docs-pr-reference.  

image

Can you please review this PR? If it looks good, then please **Squash and Merge** it into **master**. Thanks!

**Comment by lindalu-MSFT** [comment]
@kbrandl I'll merge to live now, too. Do you want to delete the branch?

**Comment by kbrandl** [comment]
Thanks, @lindalu-MSFT!

**Pull request merged**
