### PR TITLE
[Admin] Get latest changes

### PR DESCRIPTION
**Pull request by ElizabethSamuel-MSFT**

### CODE REVIEW

**Comment by AlexJerabek** [comment]
@ElizabethSamuel-MSFT, some OfficeRuntime stuff just got published. Could you please re-run the scripts to include that?

**Comment by ElizabethSamuel-MSFT** [comment]
@AlexJerabek Sure, re-running now.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[cfb360d](https://github.com/OfficeDev/office-js-docs-reference/commits/cfb360d07e6c385bbba1d77b2a9c8a10dc59fabd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/docs-ref-autogen/excel/excel/excel.worksheet.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel/excel/excel.worksheet.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook/outlook/office.attachmentcontent.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/outlook/outlook/office.attachmentcontent.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_8/outlook/office.attachmentcontent.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/outlook_1_8/outlook/office.attachmentcontent.yml) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-outlook-release/Outlook_1_8/outlook.d.ts](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/generate-docs/api-extractor-inputs-outlook-release/Outlook_1_8/outlook.d.ts) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-outlook/outlook.d.ts](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/generate-docs/api-extractor-inputs-outlook/outlook.d.ts) | :white_check_mark:Succeeded | |
[generate-docs/json/excel/snippets.yaml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/generate-docs/json/excel/snippets.yaml) | :white_check_mark:Succeeded | |
[generate-docs/json/excel_1_1/snippets.yaml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/generate-docs/json/excel_1_1/snippets.yaml) | :white_check_mark:Succeeded | |
[generate-docs/json/excel_1_10/snippets.yaml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/generate-docs/json/excel_1_10/snippets.yaml) | :white_check_mark:Succeeded | |
[generate-docs/json/excel_1_2/snippets.yaml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/generate-docs/json/excel_1_2/snippets.yaml) | :white_check_mark:Succeeded | |
[generate-docs/json/excel_1_3/snippets.yaml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/generate-docs/json/excel_1_3/snippets.yaml) | :white_check_mark:Succeeded | |
[generate-docs/json/excel_1_4/snippets.yaml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/generate-docs/json/excel_1_4/snippets.yaml) | :white_check_mark:Succeeded | |
[generate-docs/json/excel_1_5/snippets.yaml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/generate-docs/json/excel_1_5/snippets.yaml) | :white_check_mark:Succeeded | |
[generate-docs/json/excel_1_6/snippets.yaml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/generate-docs/json/excel_1_6/snippets.yaml) | :white_check_mark:Succeeded | |
[generate-docs/json/excel_1_7/snippets.yaml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/generate-docs/json/excel_1_7/snippets.yaml) | :white_check_mark:Succeeded | |
[generate-docs/json/excel_1_8/snippets.yaml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/generate-docs/json/excel_1_8/snippets.yaml) | :white_check_mark:Succeeded | |
[generate-docs/json/excel_1_9/snippets.yaml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/generate-docs/json/excel_1_9/snippets.yaml) | :white_check_mark:Succeeded | |
[generate-docs/json/excel_online/snippets.yaml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/generate-docs/json/excel_online/snippets.yaml) | :white_check_mark:Succeeded | |
[generate-docs/json/outlook/outlook.api.json](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/generate-docs/json/outlook/outlook.api.json) | :white_check_mark:Succeeded | |
[generate-docs/json/outlook_1_8/outlook.api.json](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/generate-docs/json/outlook_1_8/outlook.api.json) | :white_check_mark:Succeeded | |
[generate-docs/json/snippets.yaml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/generate-docs/json/snippets.yaml) | :white_check_mark:Succeeded | |
[generate-docs/script-inputs/local-repo-snippets.yaml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/generate-docs/script-inputs/local-repo-snippets.yaml) | :white_check_mark:Succeeded | |
[generate-docs/script-inputs/office.d.ts](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/generate-docs/script-inputs/office.d.ts) | :white_check_mark:Succeeded | |
[generate-docs/script-inputs/office_preview.d.ts](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/generate-docs/script-inputs/office_preview.d.ts) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C2%5C12%5C0e1871f2-88cb-c16b-6d81-dc80e4f66cef%5CPullRequest%5C202002121847162230-625%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MCrs%2FaZQXKJemaKNaWnylxeQ1tnde2zlYApxfrqm%2FC0%3D&st=2020-02-12T19%3A09%3A27Z&se=2020-03-14T19%3A14%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[da2a640](https://github.com/OfficeDev/office-js-docs-reference/commits/da2a640f8f758be1fd35c45e154012b84e5e579a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/docs-ref-autogen/excel/excel/excel.worksheet.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel/excel/excel.worksheet.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/office-runtime.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel/office-runtime.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/office-runtime/officeruntime.control.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel/office-runtime/officeruntime.control.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/office-runtime/officeruntime.dialog.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel/office-runtime/officeruntime.dialog.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/office-runtime/officeruntime.displaywebdialogoptions.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel/office-runtime/officeruntime.displaywebdialogoptions.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/office-runtime/officeruntime.gallery.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel/office-runtime/officeruntime.gallery.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/office-runtime/officeruntime.menucontrol.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel/office-runtime/officeruntime.menucontrol.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/office-runtime/officeruntime.ribbon.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel/office-runtime/officeruntime.ribbon.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/office-runtime/officeruntime.ribbonupdaterdata.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel/office-runtime/officeruntime.ribbonupdaterdata.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/office-runtime/officeruntime.storage.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel/office-runtime/officeruntime.storage.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/office-runtime/officeruntime.tab.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel/office-runtime/officeruntime.tab.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/office-runtime/officeruntime.ui.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel/office-runtime/officeruntime.ui.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_10/office-runtime.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel_1_10/office-runtime.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_10/office-runtime/officeruntime.control.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel_1_10/office-runtime/officeruntime.control.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_10/office-runtime/officeruntime.dialog.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel_1_10/office-runtime/officeruntime.dialog.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_10/office-runtime/officeruntime.displaywebdialogoptions.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel_1_10/office-runtime/officeruntime.displaywebdialogoptions.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_10/office-runtime/officeruntime.gallery.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel_1_10/office-runtime/officeruntime.gallery.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_10/office-runtime/officeruntime.menucontrol.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel_1_10/office-runtime/officeruntime.menucontrol.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_10/office-runtime/officeruntime.ribbon.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel_1_10/office-runtime/officeruntime.ribbon.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_10/office-runtime/officeruntime.ribbonupdaterdata.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel_1_10/office-runtime/officeruntime.ribbonupdaterdata.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_10/office-runtime/officeruntime.storage.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel_1_10/office-runtime/officeruntime.storage.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_10/office-runtime/officeruntime.tab.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel_1_10/office-runtime/officeruntime.tab.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_10/office-runtime/officeruntime.ui.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel_1_10/office-runtime/officeruntime.ui.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_10/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel_1_10/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_9/office-runtime.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel_1_9/office-runtime.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_9/office-runtime/officeruntime.control.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel_1_9/office-runtime/officeruntime.control.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_9/office-runtime/officeruntime.dialog.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel_1_9/office-runtime/officeruntime.dialog.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_9/office-runtime/officeruntime.displaywebdialogoptions.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel_1_9/office-runtime/officeruntime.displaywebdialogoptions.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_9/office-runtime/officeruntime.gallery.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel_1_9/office-runtime/officeruntime.gallery.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_9/office-runtime/officeruntime.menucontrol.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel_1_9/office-runtime/officeruntime.menucontrol.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_9/office-runtime/officeruntime.ribbon.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel_1_9/office-runtime/officeruntime.ribbon.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_9/office-runtime/officeruntime.ribbonupdaterdata.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel_1_9/office-runtime/officeruntime.ribbonupdaterdata.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_9/office-runtime/officeruntime.storage.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel_1_9/office-runtime/officeruntime.storage.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_9/office-runtime/officeruntime.tab.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel_1_9/office-runtime/officeruntime.tab.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_9/office-runtime/officeruntime.ui.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel_1_9/office-runtime/officeruntime.ui.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_9/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel_1_9/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_online/office-runtime.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel_online/office-runtime.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_online/office-runtime/officeruntime.control.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel_online/office-runtime/officeruntime.control.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_online/office-runtime/officeruntime.dialog.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel_online/office-runtime/officeruntime.dialog.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_online/office-runtime/officeruntime.displaywebdialogoptions.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel_online/office-runtime/officeruntime.displaywebdialogoptions.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_online/office-runtime/officeruntime.gallery.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel_online/office-runtime/officeruntime.gallery.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_online/office-runtime/officeruntime.menucontrol.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel_online/office-runtime/officeruntime.menucontrol.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_online/office-runtime/officeruntime.ribbon.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel_online/office-runtime/officeruntime.ribbon.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_online/office-runtime/officeruntime.ribbonupdaterdata.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel_online/office-runtime/officeruntime.ribbonupdaterdata.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_online/office-runtime/officeruntime.storage.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel_online/office-runtime/officeruntime.storage.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_online/office-runtime/officeruntime.tab.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel_online/office-runtime/officeruntime.tab.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_online/office-runtime/officeruntime.ui.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel_online/office-runtime/officeruntime.ui.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_online/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/excel_online/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook/outlook/office.attachmentcontent.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/get-latest/docs/docs-ref-autogen/outlook/outlook/office.attachmentcontent.yml) | :white_check_mark:Succeeded | |

This comment lists only the first 50 files in the pull request.
For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C2%5C12%5C0e1871f2-88cb-c16b-6d81-dc80e4f66cef%5CPullRequest%5C202002121914218490-625%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5ss2vKpbG9y13fSKT67Meuuydyqss45pbCs6SHCXK%2FM%3D&st=2020-02-12T19%3A35%3A56Z&se=2020-03-14T19%3A40%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
