### PR TITLE
Removing the term "relationship" from the overviews

### PR DESCRIPTION
**Pull request by AlexJerabek**
Relationships aren't a concept in the new reference docs. Updating the overviews to reflect the information we're now presenting.

### CODE REVIEW

**Comment by o365devx** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.redirection.json](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-Relationships/.openpublishing.redirection.json) | :x:Error | | [Details](#user-content-.openpublishing.redirection.json)

<a name=".openpublishing.redirection.json"></a>
### [.openpublishing.redirection.json](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-Relationships/.openpublishing.redirection.json)
 - **[Error]** source_path &#39;docs/docs-ref-autogen/word/word.word-add-ins-reference-overview.yml&#39; in master redirection file should point to a file of extension &#39;.md&#39;.
Learn more: https://opsdocs.azurewebsites.net/en-us/opsdocs/partnerdocs/opredirection?branch=master#3-master-redirection-file.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C20%5C0e1871f2-88cb-c16b-6d81-dc80e4f66cef%5CPullRequest%5C201808202240288831-125%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=7rKESFLoyHgtpM0AAhRunKdFEeBOg%2F6Hqelv0u%2BAkfs%3D&st=2018-08-20T22%3A36%3A10Z&se=2018-09-20T22%3A41%3A10Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Rick-Kirkham** [comment]
@AlexJerabek I think so. MZ or Juan would know for sure.

**Comment by o365devx** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/docs-ref-conceptual/overview/visio-javascript-reference-overview.md](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-Relationships/docs/docs-ref-conceptual/overview/visio-javascript-reference-overview.md) | :warning:Warning | | [Details](#user-content-docs%2Fdocs-ref-conceptual%2Foverview%2Fvisio-javascript-reference-overview.md)
[docs/docs-ref-conceptual/overview/excel-add-ins-reference-overview.md](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-Relationships/docs/docs-ref-conceptual/overview/excel-add-ins-reference-overview.md) | :white_check_mark:Succeeded | |
[docs/docs-ref-conceptual/overview/onenote-add-ins-javascript-reference.md](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-Relationships/docs/docs-ref-conceptual/overview/onenote-add-ins-javascript-reference.md) | :white_check_mark:Succeeded | |

<a name="docs%2Fdocs-ref-conceptual%2Foverview%2Fvisio-javascript-reference-overview.md"></a>
### [docs/docs-ref-conceptual/overview/visio-javascript-reference-overview.md](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-Relationships/docs/docs-ref-conceptual/overview/visio-javascript-reference-overview.md)
 - **Line 0**: **[Warning]** Invalid file link:(~/docs-ref-conceptual/images/visio-api-block-diagram.png).
 - **Line 0**: **[Warning]** Invalid file link:(~/docs-ref-conceptual/images/Visio-embed-url.png).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C20%5C0e1871f2-88cb-c16b-6d81-dc80e4f66cef%5CPullRequest%5C201808202332486180-125%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=hyJwfi9b8J9Y%2BoiiZLlKdHN2L8zLLjocaV6EQWxweZY%3D&st=2018-08-20T23%3A32%3A51Z&se=2018-09-20T23%3A37%3A51Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by AlexJerabek** [comment]
Opened [2508833](https://office.visualstudio.com/OC/_workitems/edit/2508833) to track this.

**Pull request merged**
