### PR TITLE
Programmatically determining enum lists per host

### PR DESCRIPTION
**Pull request by AlexJerabek**
To avoid constantly updating these lists, the postprocessor script can now use the TypeScript compiler to look for enums.

### CODE REVIEW

**Comment by o365devx** [comment]
OPS Build status updates of commit _[e070348](https://github.com/OfficeDev/office-js-docs-reference/pull/289/commits/e070348a4fde6e8c133a08c2246a86d179de495c)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 2 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[e070348](https://github.com/OfficeDev/office-js-docs-reference/pull/289/commits/e070348a4fde6e8c133a08c2246a86d179de495c)_: 

:clock10: **Incremental building**: average incremental building time is _5 min(s) 2 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[e070348](https://github.com/OfficeDev/office-js-docs-reference/pull/289/commits/e070348a4fde6e8c133a08c2246a86d179de495c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/docs-ref-autogen/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-Enum/docs/docs-ref-autogen/toc.yml) | :white_check_mark:Succeeded | |
[generate-docs/scripts/postprocessor.ts](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-Enum/generate-docs/scripts/postprocessor.ts) | :white_check_mark:Succeeded | |
[generate-docs/scripts/util.ts](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-Enum/generate-docs/scripts/util.ts) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C15%5C0e1871f2-88cb-c16b-6d81-dc80e4f66cef%5CPullRequest%5C201901152157273883-289%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=qhHPTesipsjEECUn1qckWnWANVJFd%2F66It5Sz25hnvU%3D&st=2019-01-15T21%3A58%3A19Z&se=2019-02-15T22%3A03%3A19Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
OPS Build status updates of commit _[4e2504d](https://github.com/OfficeDev/office-js-docs-reference/pull/289/commits/4e2504dae7440832c9a50509da696747d2c11cdd)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 2 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[4e2504d](https://github.com/OfficeDev/office-js-docs-reference/pull/289/commits/4e2504dae7440832c9a50509da696747d2c11cdd)_: 

:clock10: **Incremental building**: average incremental building time is _5 min(s)_

**Comment by kbrandl** [comment]
@AlexJerabek a high-level scan of the changes looks okay to me (although admittedly, I'm not super familiar with any of the recent changes to the d.ts file, so I can't really judge whether or not those changes are reflected accurately here). Feel free to merge if the scope of changes in this PR looks right to you.

**Pull request merged**
