### PR TITLE
Updating with the latest CDN content

### PR DESCRIPTION
**Pull request by AlexJerabek**
This changes the `load` text for Excel, so there are many changed files. I'll post the staging site link once it builds.

### CODE REVIEW

**Comment by o365devx** [comment]
Docs Build status updates of commit _[e9c5f3a](https://github.com/OfficeDev/office-js-docs-reference/commits/e9c5f3a9ac91ecd41428cd5c6670dcb4d173db91)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/docs-ref-autogen/excel/excel.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.application.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.application.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.autofilter.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.autofilter.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.binding.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.binding.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.bindingcollection.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.bindingcollection.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.cellvalueconditionalformat.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.cellvalueconditionalformat.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chart.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chart.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartareaformat.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartareaformat.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartaxes.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartaxes.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartaxis.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartaxis.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartaxisformat.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartaxisformat.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartaxistitle.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartaxistitle.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartaxistitleformat.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartaxistitleformat.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartbinoptions.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartbinoptions.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartborder.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartborder.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartboxwhiskeroptions.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartboxwhiskeroptions.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartcollection.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartcollection.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartdatalabel.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartdatalabel.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartdatalabelformat.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartdatalabelformat.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartdatalabels.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartdatalabels.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.charterrorbars.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.charterrorbars.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.charterrorbarsformat.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.charterrorbarsformat.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartfill.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartfill.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartfont.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartfont.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartformatstring.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartformatstring.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartgridlines.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartgridlines.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartgridlinesformat.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartgridlinesformat.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartlegend.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartlegend.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartlegendentry.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartlegendentry.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartlegendentrycollection.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartlegendentrycollection.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartlegendformat.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartlegendformat.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartlineformat.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartlineformat.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartmapoptions.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartmapoptions.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartpivotoptions.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartpivotoptions.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartplotarea.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartplotarea.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartplotareaformat.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartplotareaformat.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartpoint.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartpoint.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartpointformat.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartpointformat.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartpointscollection.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartpointscollection.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartseries.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartseries.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartseriescollection.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartseriescollection.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartseriesformat.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartseriesformat.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.charttitle.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.charttitle.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.charttitleformat.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.charttitleformat.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.charttrendline.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.charttrendline.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.charttrendlinecollection.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.charttrendlinecollection.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.charttrendlineformat.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.charttrendlineformat.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.charttrendlinelabel.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.charttrendlinelabel.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.charttrendlinelabelformat.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.charttrendlinelabelformat.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.colorscaleconditionalformat.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.colorscaleconditionalformat.yml) | :white_check_mark:Succeeded | |

This comment lists only the first 50 files in the pull request.
For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C9%5C24%5C0e1871f2-88cb-c16b-6d81-dc80e4f66cef%5CPullRequest%5C201909242303142422-516%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nV7GLx8WtamRyewfi9lO4WBA8SItr0B4Wm8mgfdxaqM%3D&st=2019-09-24T23%3A19%3A57Z&se=2019-10-25T23%3A24%3A57Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by AlexJerabek** [comment]
[Staging site link](https://review.docs.microsoft.com/en-us/javascript/api/overview?branch=AlexJ-DT&view=excel-js-preview)

**Comment by AlexJerabek** [comment]
@ElizabethSamuel-MSFT Added the latest Outlook content from Definitely Typed.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[27ee884](https://github.com/OfficeDev/office-js-docs-reference/commits/27ee884afe8d271e2c99357b968df92d97f03481)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/docs-ref-autogen/excel/excel.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.application.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.application.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.autofilter.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.autofilter.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.binding.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.binding.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.bindingcollection.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.bindingcollection.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.cellvalueconditionalformat.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.cellvalueconditionalformat.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chart.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chart.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartareaformat.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartareaformat.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartaxes.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartaxes.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartaxis.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartaxis.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartaxisformat.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartaxisformat.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartaxistitle.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartaxistitle.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartaxistitleformat.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartaxistitleformat.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartbinoptions.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartbinoptions.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartborder.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartborder.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartboxwhiskeroptions.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartboxwhiskeroptions.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartcollection.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartcollection.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartdatalabel.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartdatalabel.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartdatalabelformat.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartdatalabelformat.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartdatalabels.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartdatalabels.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.charterrorbars.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.charterrorbars.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.charterrorbarsformat.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.charterrorbarsformat.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartfill.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartfill.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartfont.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartfont.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartformatstring.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartformatstring.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartgridlines.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartgridlines.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartgridlinesformat.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartgridlinesformat.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartlegend.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartlegend.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartlegendentry.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartlegendentry.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartlegendentrycollection.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartlegendentrycollection.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartlegendformat.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartlegendformat.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartlineformat.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartlineformat.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartmapoptions.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartmapoptions.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartpivotoptions.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartpivotoptions.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartplotarea.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartplotarea.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartplotareaformat.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartplotareaformat.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartpoint.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartpoint.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartpointformat.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartpointformat.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartpointscollection.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartpointscollection.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartseries.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartseries.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartseriescollection.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartseriescollection.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.chartseriesformat.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.chartseriesformat.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.charttitle.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.charttitle.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.charttitleformat.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.charttitleformat.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.charttrendline.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.charttrendline.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.charttrendlinecollection.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.charttrendlinecollection.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.charttrendlineformat.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.charttrendlineformat.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.charttrendlinelabel.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.charttrendlinelabel.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.charttrendlinelabelformat.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.charttrendlinelabelformat.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel/excel.colorscaleconditionalformat.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-DT/docs/docs-ref-autogen/excel/excel/excel.colorscaleconditionalformat.yml) | :white_check_mark:Succeeded | |

This comment lists only the first 50 files in the pull request.
For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C9%5C25%5C0e1871f2-88cb-c16b-6d81-dc80e4f66cef%5CPullRequest%5C201909252133193790-516%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=J8EIZ4GG%2BfFCLN%2FVGiz61xfsFfpKCPPaMGfmEdSAVqM%3D&st=2019-09-25T21%3A49%3A14Z&se=2019-10-26T21%3A54%3A14Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
