### PR TITLE
[Prototype] (monikers) Experiments with API Ref landing page

### PR DESCRIPTION
**Pull request by kbrandl**

### CODE REVIEW

**Comment by o365devx** [comment]
OPS Build status updates of commit _[6a915a3](https://github.com/OfficeDev/office-js-docs-reference/pull/341/commits/6a915a3a3efa92205319cdcdb4c69f8c30348c9e)_: 

:clock10: **Preparing**: average preparing time is _1 min(s)_

**Comment by kbrandl** [comment]
@AlexJerabek FYI, I'm merging my landing-page-related changes into your branch. I'm sending you an email now with details about this; shouldn't cause any disruption on your end.

**Comment by o365devx** [comment]
OPS Build status updates of commit _[6a915a3](https://github.com/OfficeDev/office-js-docs-reference/pull/341/commits/6a915a3a3efa92205319cdcdb4c69f8c30348c9e)_: 

:clock10: **Incremental building**: average incremental building time is _4 min(s) 48 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[6a915a3](https://github.com/OfficeDev/office-js-docs-reference/pull/341/commits/6a915a3a3efa92205319cdcdb4c69f8c30348c9e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/docfx.json](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docfx.json) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/api-ref-office-js.md](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/excel/api-ref-office-js.md) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/excel/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_1/api-ref-office-js.md](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/excel_1_1/api-ref-office-js.md) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_1/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/excel_1_1/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_2/api-ref-office-js.md](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/excel_1_2/api-ref-office-js.md) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_2/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/excel_1_2/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_3/api-ref-office-js.md](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/excel_1_3/api-ref-office-js.md) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_3/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/excel_1_3/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_4/api-ref-office-js.md](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/excel_1_4/api-ref-office-js.md) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_4/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/excel_1_4/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_5/api-ref-office-js.md](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/excel_1_5/api-ref-office-js.md) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_5/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/excel_1_5/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_6/api-ref-office-js.md](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/excel_1_6/api-ref-office-js.md) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_6/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/excel_1_6/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_7/api-ref-office-js.md](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/excel_1_7/api-ref-office-js.md) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_7/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/excel_1_7/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_8/api-ref-office-js.md](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/excel_1_8/api-ref-office-js.md) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_1_8/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/excel_1_8/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/images/api-ref-moniker-selector-1.png](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/images/api-ref-moniker-selector-1.png) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/images/api-ref-moniker-selector-2.png](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/images/api-ref-moniker-selector-2.png) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/onenote/api-ref-office-js.md](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/onenote/api-ref-office-js.md) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/onenote/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/onenote/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook/api-ref-office-js.md](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/outlook/api-ref-office-js.md) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/outlook/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_1/api-ref-office-js.md](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/outlook_1_1/api-ref-office-js.md) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_1/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/outlook_1_1/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_2/api-ref-office-js.md](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/outlook_1_2/api-ref-office-js.md) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_2/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/outlook_1_2/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_3/api-ref-office-js.md](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/outlook_1_3/api-ref-office-js.md) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_3/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/outlook_1_3/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_4/api-ref-office-js.md](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/outlook_1_4/api-ref-office-js.md) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_4/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/outlook_1_4/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_5/api-ref-office-js.md](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/outlook_1_5/api-ref-office-js.md) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_5/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/outlook_1_5/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_6/api-ref-office-js.md](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/outlook_1_6/api-ref-office-js.md) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_6/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/outlook_1_6/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_7/api-ref-office-js.md](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/outlook_1_7/api-ref-office-js.md) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_7/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/outlook_1_7/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/overview/api-ref-office-js.md](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/overview/api-ref-office-js.md) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/overview/images/api-ref-moniker-selector-1.png](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/overview/images/api-ref-moniker-selector-1.png) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/overview/images/api-ref-moniker-selector-2.png](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/overview/images/api-ref-moniker-selector-2.png) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/powerpoint/api-ref-office-js.md](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/powerpoint/api-ref-office-js.md) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/powerpoint/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/powerpoint/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/visio/api-ref-office-js.md](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/visio/api-ref-office-js.md) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/visio/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/visio/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/word/api-ref-office-js.md](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/word/api-ref-office-js.md) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/word/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/word/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/word_1_1/api-ref-office-js.md](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/word_1_1/api-ref-office-js.md) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/word_1_1/toc.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/kb-monikers-test/docs/docs-ref-autogen/word_1_1/toc.yml) | :white_check_mark:Succeeded | |

This comment lists only the first 50 files in the pull request.
For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C2%5C0e1871f2-88cb-c16b-6d81-dc80e4f66cef%5CPullRequest%5C201903020053448701-341%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=sRuWiKGMiL3%2FopJKYguV6OBQRKipjlH7uT5gHVjMGZM%3D&st=2019-03-02T01%3A14%3A32Z&se=2019-04-02T01%3A19%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
