### PR TITLE
Better table generation for WhatsNew tool

### PR DESCRIPTION
**Pull request by AlexJerabek**
This makes the function signatures and descriptions equal width for the whole set.

### CODE REVIEW

**Comment by o365devx** [comment]
OPS Build status updates of commit _[f5ce51d](https://github.com/OfficeDev/office-js-docs-reference/pull/279/commits/f5ce51dcfde786277bb6a9f91904bf5d46197627)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 3 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[f5ce51d](https://github.com/OfficeDev/office-js-docs-reference/pull/279/commits/f5ce51dcfde786277bb6a9f91904bf5d46197627)_: 

:clock10: **Incremental building**: average incremental building time is _4 min(s) 59 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[f5ce51d](https://github.com/OfficeDev/office-js-docs-reference/pull/279/commits/f5ce51dcfde786277bb6a9f91904bf5d46197627)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[generate-docs/tools/WhatsNew.ts](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-Test/generate-docs/tools/WhatsNew.ts) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C3%5C0e1871f2-88cb-c16b-6d81-dc80e4f66cef%5CPullRequest%5C201901022358448581-279%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=EvblsCLE1mdg8LhMqnGqNzet3S1bG71kpX%2FHtDPhO%2F8%3D&st=2019-01-02T23%3A59%3A54Z&se=2019-02-03T00%3A04%3A54Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
OPS Build status updates of commit _[4ad5f65](https://github.com/OfficeDev/office-js-docs-reference/pull/279/commits/4ad5f651021669613d9ea74a46bbe79c3a7a5989)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 3 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[4ad5f65](https://github.com/OfficeDev/office-js-docs-reference/pull/279/commits/4ad5f651021669613d9ea74a46bbe79c3a7a5989)_: 

:clock10: **Incremental building**: average incremental building time is _4 min(s) 59 sec(s)_

**Comment by AlexJerabek** [comment]
Thanks for catching that @kbrandl. Updated to fix the method links. Here's some sample output:

|Class|Fields|Description|
|:---|:---|:---|
|[AutoFilter](/javascript/api/excel/excel.autofilter)|[apply(range: Range \| string, columnIndex?: number, criteria?: Excel.FilterCriteria)](/javascript/api/excel/excel.autofilter#apply-range--columnindex--criteria-)|Applies AutoFilter on a range and filters the column if column index and filter criteria are specified.|
||[clearCriteria()](/javascript/api/excel/excel.autofilter#clearcriteria--)|Clears the criteria if AutoFilter has filters|
||[getRange()](/javascript/api/excel/excel.autofilter#getrange--)|Returns the Range object that represents the range to which the AutoFilter applies.|
||[getRangeOrNullObject()](/javascript/api/excel/excel.autofilter#getrangeornullobject--)|If there is Range object associated with the AutoFilter, this method returns it.|
||[criteria](/javascript/api/excel/excel.autofilter#criteria)|Array that holds all filter criterias in an autofiltered range. Read-Only.|
||[enabled](/javascript/api/excel/excel.autofilter#enabled)|Indicates if the AutoFilter is enabled or not. Read-Only.|
||[isDataFiltered](/javascript/api/excel/excel.autofilter#isdatafiltered)|Indicates if the AutoFilter has filter criteria. Read-Only.|
||[reapply()](/javascript/api/excel/excel.autofilter#reapply--)|Applies the specified Autofilter object currently on the range.|
||[remove()](/javascript/api/excel/excel.autofilter#remove--)|Removes the AutoFilter for the range.|

**Comment by o365devx** [comment]
OPS Build status updates of commit _[4ad5f65](https://github.com/OfficeDev/office-js-docs-reference/pull/279/commits/4ad5f651021669613d9ea74a46bbe79c3a7a5989)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[generate-docs/tools/WhatsNew.ts](https://github.com/OfficeDev/office-js-docs-reference/blob/AlexJ-Test/generate-docs/tools/WhatsNew.ts) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C3%5C0e1871f2-88cb-c16b-6d81-dc80e4f66cef%5CPullRequest%5C201901032006327615-279%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=PpTP599%2BfSmn6XMjN%2FimnJ3qJZoCVTIY3uqGPBMCOG4%3D&st=2019-01-03T20%3A08%3A15Z&se=2019-02-03T20%3A13%3A15Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
