### PR TITLE
update redirection file

### PR DESCRIPTION
**Pull request by ElizabethSamuel-MSFT**

### CODE REVIEW

**Comment by o365devx** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/docs-ref-conceptual/overview/visio-javascript-reference-overview.md](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-update-redirect-file/docs/docs-ref-conceptual/overview/visio-javascript-reference-overview.md) | :warning:Warning | | [Details](#user-content-docs%2Fdocs-ref-conceptual%2Foverview%2Fvisio-javascript-reference-overview.md)
[.openpublishing.redirection.json](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-update-redirect-file/.openpublishing.redirection.json) | :white_check_mark:Succeeded | |

<a name="docs%2Fdocs-ref-conceptual%2Foverview%2Fvisio-javascript-reference-overview.md"></a>
### [docs/docs-ref-conceptual/overview/visio-javascript-reference-overview.md](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-update-redirect-file/docs/docs-ref-conceptual/overview/visio-javascript-reference-overview.md)
 - **Line 0**: **[Warning]** Invalid file link:(~/docs-ref-conceptual/images/visio-api-block-diagram.png).
 - **Line 0**: **[Warning]** Invalid file link:(~/docs-ref-conceptual/images/Visio-embed-url.png).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C20%5C0e1871f2-88cb-c16b-6d81-dc80e4f66cef%5CPullRequest%5C201808202117054468-123%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=kb6KU0avRHxfZ4hjurZirie3k1TSqvPmlwZ7ku07Asw%3D&st=2018-08-20T21%3A17%3A05Z&se=2018-09-20T21%3A22%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Linda-Editor** [comment]
Elizabeth, why are you redirecting this file? I don't even see it in the repo...

**Comment by AlexJerabek** [comment]
@ElizabethSamuel-MSFT Why is this json file causing build failures? Shouldn't we push this change? (or remove the file altogether)

**Comment by ElizabethSamuel-MSFT** [comment]
@AlexJerabek : Sorry about that. Let me finish this stage of verification.

**Comment by o365devx** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/docs-ref-conceptual/overview/visio-javascript-reference-overview.md](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-update-redirect-file/docs/docs-ref-conceptual/overview/visio-javascript-reference-overview.md) | :warning:Warning | | [Details](#user-content-docs%2Fdocs-ref-conceptual%2Foverview%2Fvisio-javascript-reference-overview.md)
[.openpublishing.redirection.json](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-update-redirect-file/.openpublishing.redirection.json) | :white_check_mark:Succeeded | |

<a name="docs%2Fdocs-ref-conceptual%2Foverview%2Fvisio-javascript-reference-overview.md"></a>
### [docs/docs-ref-conceptual/overview/visio-javascript-reference-overview.md](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-update-redirect-file/docs/docs-ref-conceptual/overview/visio-javascript-reference-overview.md)
 - **Line 0**: **[Warning]** Invalid file link:(~/docs-ref-conceptual/images/visio-api-block-diagram.png).
 - **Line 0**: **[Warning]** Invalid file link:(~/docs-ref-conceptual/images/Visio-embed-url.png).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C20%5C0e1871f2-88cb-c16b-6d81-dc80e4f66cef%5CPullRequest%5C201808202249105203-123%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=UyQZN0cOl%2BCULDGm51vEjwWCAfEfpRBvQgCEW3vTaHA%3D&st=2018-08-20T22%3A49%3A06Z&se=2018-09-20T22%3A54%3A06Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by AlexJerabek** [comment]
@ElizabethSamuel-MSFT  This seems fine to me, but what's the context for this change? Just for my own learning :-)

**Comment by ElizabethSamuel-MSFT** [comment]
@AlexJerabek : This is part of the redirection work with Arvind. Some of the files don't fit the wildcard patterns so this is for the exceptions.

**Comment by o365devx** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/docs-ref-conceptual/overview/visio-javascript-reference-overview.md](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-update-redirect-file/docs/docs-ref-conceptual/overview/visio-javascript-reference-overview.md) | :warning:Warning | | [Details](#user-content-docs%2Fdocs-ref-conceptual%2Foverview%2Fvisio-javascript-reference-overview.md)
[.openpublishing.redirection.json](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-update-redirect-file/.openpublishing.redirection.json) | :white_check_mark:Succeeded | |

<a name="docs%2Fdocs-ref-conceptual%2Foverview%2Fvisio-javascript-reference-overview.md"></a>
### [docs/docs-ref-conceptual/overview/visio-javascript-reference-overview.md](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-update-redirect-file/docs/docs-ref-conceptual/overview/visio-javascript-reference-overview.md)
 - **Line 0**: **[Warning]** Invalid file link:(~/docs-ref-conceptual/images/visio-api-block-diagram.png).
 - **Line 0**: **[Warning]** Invalid file link:(~/docs-ref-conceptual/images/Visio-embed-url.png).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C20%5C0e1871f2-88cb-c16b-6d81-dc80e4f66cef%5CPullRequest%5C201808202249205204-123%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ZH8blXwYlmkRTz2sEgHblZV5CQgAc7j1CV3c7E5GIPw%3D&st=2018-08-20T22%3A53%3A53Z&se=2018-09-20T22%3A58%3A53Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lindalu-MSFT** [comment]
@ElizabethSamuel-MSFT Do you want me to merge this to live today?

**Pull request merged**
