### PR TITLE
[Outlook] (snippets) Update snippets mapping and refresh legacy

### PR DESCRIPTION
**Pull request by ElizabethSamuel-MSFT**
This is for the snippets I added recently.

### CODE REVIEW

**Comment by o365devx** [comment]
OPS Build status updates of commit _[d4182b9](https://github.com/OfficeDev/office-js-docs-reference/pull/318/commits/d4182b9bafb3b52eba6ad362c51f6a72e7c4f821)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 1 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[d4182b9](https://github.com/OfficeDev/office-js-docs-reference/pull/318/commits/d4182b9bafb3b52eba6ad362c51f6a72e7c4f821)_: 

:clock10: **Incremental building**: average incremental building time is _4 min(s) 59 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[d4182b9](https://github.com/OfficeDev/office-js-docs-reference/pull/318/commits/d4182b9bafb3b52eba6ad362c51f6a72e7c4f821)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/code-snippets/outlook-snippets.yaml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/code-snippets/outlook-snippets.yaml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook/office.enhancedlocation.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/docs-ref-autogen/outlook/office.enhancedlocation.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook/office.from.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/docs-ref-autogen/outlook/office.from.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook/office.internetheaders.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/docs-ref-autogen/outlook/office.internetheaders.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook/office.item.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/docs-ref-autogen/outlook/office.item.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook/office.location.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/docs-ref-autogen/outlook/office.location.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook/office.recipients.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/docs-ref-autogen/outlook/office.recipients.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook/office.recurrence.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/docs-ref-autogen/outlook/office.recurrence.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook/office.subject.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/docs-ref-autogen/outlook/office.subject.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook/office.time.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/docs-ref-autogen/outlook/office.time.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_1/office.location.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/docs-ref-autogen/outlook_1_1/office.location.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_1/office.recipients.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/docs-ref-autogen/outlook_1_1/office.recipients.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_1/office.subject.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/docs-ref-autogen/outlook_1_1/office.subject.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_1/office.time.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/docs-ref-autogen/outlook_1_1/office.time.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_2/office.location.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/docs-ref-autogen/outlook_1_2/office.location.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_2/office.recipients.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/docs-ref-autogen/outlook_1_2/office.recipients.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_2/office.subject.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/docs-ref-autogen/outlook_1_2/office.subject.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_2/office.time.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/docs-ref-autogen/outlook_1_2/office.time.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_3/office.location.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/docs-ref-autogen/outlook_1_3/office.location.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_3/office.recipients.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/docs-ref-autogen/outlook_1_3/office.recipients.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_3/office.subject.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/docs-ref-autogen/outlook_1_3/office.subject.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_3/office.time.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/docs-ref-autogen/outlook_1_3/office.time.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_4/office.location.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/docs-ref-autogen/outlook_1_4/office.location.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_4/office.recipients.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/docs-ref-autogen/outlook_1_4/office.recipients.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_4/office.subject.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/docs-ref-autogen/outlook_1_4/office.subject.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_4/office.time.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/docs-ref-autogen/outlook_1_4/office.time.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_5/office.location.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/docs-ref-autogen/outlook_1_5/office.location.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_5/office.recipients.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/docs-ref-autogen/outlook_1_5/office.recipients.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_5/office.subject.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/docs-ref-autogen/outlook_1_5/office.subject.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_5/office.time.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/docs-ref-autogen/outlook_1_5/office.time.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_6/office.location.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/docs-ref-autogen/outlook_1_6/office.location.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_6/office.recipients.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/docs-ref-autogen/outlook_1_6/office.recipients.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_6/office.subject.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/docs-ref-autogen/outlook_1_6/office.subject.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_6/office.time.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/docs-ref-autogen/outlook_1_6/office.time.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_7/office.from.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/docs-ref-autogen/outlook_1_7/office.from.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_7/office.item.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/docs-ref-autogen/outlook_1_7/office.item.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_7/office.location.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/docs-ref-autogen/outlook_1_7/office.location.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_7/office.recipients.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/docs-ref-autogen/outlook_1_7/office.recipients.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_7/office.recurrence.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/docs-ref-autogen/outlook_1_7/office.recurrence.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_7/office.subject.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/docs-ref-autogen/outlook_1_7/office.subject.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook_1_7/office.time.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/docs/docs-ref-autogen/outlook_1_7/office.time.yml) | :white_check_mark:Succeeded | |
[generate-docs/GenerateDocs.cmd](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/generate-docs/GenerateDocs.cmd) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_1/Outlook_1_1.d.ts](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_1/Outlook_1_1.d.ts) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_2/Outlook_1_2.d.ts](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_2/Outlook_1_2.d.ts) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_3/Outlook_1_3.d.ts](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_3/Outlook_1_3.d.ts) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_4/Outlook_1_4.d.ts](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_4/Outlook_1_4.d.ts) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_5/Outlook_1_5.d.ts](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_5/Outlook_1_5.d.ts) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_6/Outlook_1_6.d.ts](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_6/Outlook_1_6.d.ts) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_7/Outlook_1_7.d.ts](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_7/Outlook_1_7.d.ts) | :white_check_mark:Succeeded | |
[generate-docs/json/snippets.yaml](https://github.com/OfficeDev/office-js-docs-reference/blob/elizs-refresh-legacy/generate-docs/json/snippets.yaml) | :white_check_mark:Succeeded | |

This comment lists only the first 50 files in the pull request.
For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C11%5C0e1871f2-88cb-c16b-6d81-dc80e4f66cef%5CPullRequest%5C201902112203042168-318%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Z8WGtLwxknf7JRr7x%2FxHHyk4qs5XzfaCfISuHVTPc7A%3D&st=2019-02-11T22%3A02%3A27Z&se=2019-03-14T22%3A07%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by ElizabethSamuel-MSFT** [comment]
@AlexJerabek: Yes, pretty much.

**Pull request merged**
