### PR TITLE
Update postprocessor to handle yml output changes for latest API Documenter version

### PR DESCRIPTION
**Pull request by AlexJerabek**
API Documenter produces different yml for nested namespaces after the 7.6 update. Given our level of TOC manipulation, this posed a significant challenge for our tooling to absorb these changes. This change looks to address that and get this repo on the latest versions of the tooling.

The main changes are in the postprocessor. Considering the large scale of the yml changes (most of which is cosmetic spacing differences), I'd ask area owners to spot check their API reference docs.
- @alison-mk, Please check [Excel and custom functions](https://review.docs.microsoft.com/en-us/javascript/api/excel?view=excel-js-preview&branch=AlexJ-RSTools)
- @ElizabethSamuel-MSFT, Please check [Outlook ](https://review.docs.microsoft.com/en-us/javascript/api/outlook?view=outlook-js-preview&branch=AlexJ-RSTools) and [Word](https://review.docs.microsoft.com/en-us/javascript/api/word?view=word-js-preview&branch=AlexJ-RSTools).  
- @Rick-Kirkham, Please check [PowerPoint](https://review.docs.microsoft.com/en-us/javascript/api/powerpoint?view=powerpoint-js-preview&branch=AlexJ-RSTools) and the [Common APIs](https://review.docs.microsoft.com/en-us/javascript/api/office?view=powerpoint-js-preview&branch=AlexJ-RSTools). 

Note that a larger request to address the nested namespace display is tracked here: https://github.com/microsoft/rushstack/issues/2564

### CODE REVIEW

**Comment by Rick-Kirkham** [comment]
The formatting of https://review.docs.microsoft.com/en-us/javascript/api/office/office.ui?view=powerpoint-js-preview&branch=AlexJ-RSTools goes haywire near the end of the first overload of `displayDialogAsync` in the subsection titled **displayDialogAsync Errors** (under the **Remarks** section).

**Review by Rick-Kirkham — CHANGES_REQUESTED** [review]
Seem my specific comment. That is the only problem page I saw after spot checking. Youm might want to try to find all pages that have a table in the **Remarks** section to see if a similar problem is in them.

**Comment by Rick-Kirkham** [comment]
Spoke too soon. Found a ToC anomaly. In the existing ToC the 3 items marked in red in this screen shot are subitems in a folder called Addin Commands

image

**Comment by AlexJerabek** [comment]
Thanks @Rick-Kirkham. I'm going to close this PR while I debug the UI page you found.

**Comment by ElizabethSamuel-MSFT** [comment]
> The formatting of https://review.docs.microsoft.com/en-us/javascript/api/office/office.ui?view=powerpoint-js-preview&branch=AlexJ-RSTools goes haywire near the end of the first overload of `displayDialogAsync` in the subsection titled **displayDialogAsync Errors** (under the **Remarks** section). The ToC breaks on that article too. Most of it is hidden at it is not scrollable.

That entire page seems messed up. Additionally, the table in the Methods section is not formatted correctly.

For comparison, there's a table in the [Office.Recurrence](https://docs.microsoft.com/javascript/api/outlook/office.recurrence?view=outlook-js-preview) interface-level Remarks section that displayed well. There's also a table in the [Office.UserProfile.accountType](https://docs.microsoft.com/javascript/api/outlook/office.userprofile?view=outlook-js-preview#accountType) Remarks section that's looking good to me.

**Comment by AlexJerabek** [comment]
@ElizabethSamuel-MSFT @Rick-Kirkham Looks like it's the `<AppDomain>` text in that table. Here's the row from the .d.ts:

```
 <tr>
        *     <td>12004</td>
        *     <td>The domain of the URL passed to displayDialogAsync is not trusted. The domain must be either the same domain as the host page (including protocol and port number), or it must be registered in the <AppDomains> section of the add-in manifest.</td>
        *   </tr>
```

And here's what's currently in master. Note the missing `<AppDomains>`:

image


Removing the angle brackets seems to allow the table to parse correctly. It's almost as if `<AppDomains>` is a special symbol in OPS.

I'll need to make the corresponding change in DefinitelyTyped to continue.

**Review by Rick-Kirkham — APPROVED** [review]

**Review by alison-mk — APPROVED** [review]

**Review by ElizabethSamuel-MSFT — APPROVED** [review]

**Pull request merged**
