### PR TITLE
[Excel] (Custom functions) Adding a custom functions snippet for Error and ErrorCode

### PR DESCRIPTION
**Pull request by alison-mk**
[Internal work item](https://office.visualstudio.com/OC/_workitems/edit/6176010). This PR is a test branch for updating the ref docs generation process to support custom functions snippets.

Running `sh GenerateDocs.sh` and choosing the DefinitelyTyped (full rebuild) option with the custom-functions-snippets.yaml file in this branch returns the following error.

image

### CODE REVIEW

**Comment by alison-mk** [comment]
@ElizabethSamuel-MSFT Can you tell if the samples mapped properly? It seems like it, despite the error I saw

**Comment by ElizabethSamuel-MSFT** [comment]
> @ElizabethSamuel-MSFT Can you tell if the samples mapped properly? It seems like it, despite the error I saw

@alison-mk I'm not seeing the samples in the CustomFunctions.Error.yaml and CustomFunctions.ErrorCode.yaml files so it looks like that mapping didn't happen

**Comment by alison-mk** [comment]
@AlexJerabek Could you review this PR? @ElizabethSamuel-MSFT updated generate-docs/scripts/midprocessor.ts and we think the docs generation process is working for custom functions ref docs samples now! Would be great to get another pair of eyes on this to confirm, though.

**Review by AlexJerabek — APPROVED** [review]
Looks like it's working fine! Next step, Script Lab snippet inclusion.

**Pull request merged**
