### PR TITLE
Publish doc updates

### PR DESCRIPTION
**Pull request by kbrandl**

### CODE REVIEW

**Comment by AlexJerabek** [comment]
@kbrandl Can I add #455 to this live push?

**Comment by o365devx** [comment]
Docs Build status updates of commit _[6282936](https://github.com/OfficeDev/office-js-docs-reference/pull/456/commits/6282936a4a3a759d4b3cbcd44cbc5146ae98f25a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/docs-ref-autogen/custom-functions-runtime/customfunctions.streaminginvocation.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/custom-functions-runtime/customfunctions.streaminginvocation.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/excel.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel.interfaces.functionresultdata.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/excel/excel.interfaces.functionresultdata.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_release.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/excel_release.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_release/excel.interfaces.functionresultdata.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/excel_release/excel.interfaces.functionresultdata.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/office/office.asyncresult.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/office/office.asyncresult.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/office/office.binding.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/office/office.binding.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/office/office.document.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/office/office.document.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/office/office.ipromiseconstructor.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/office/office.ipromiseconstructor.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/office/officeextension.clientrequestcontext.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/office/officeextension.clientrequestcontext.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/office/officeextension.eventinfo.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/office/officeextension.eventinfo.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/office/officeextension.runoptions.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/office/officeextension.runoptions.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/onenote.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/onenote.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook/office.sharedproperties.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/outlook/office.sharedproperties.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/visio.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/visio.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/word.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/word.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/word_release.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/word_release.yml) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-custom-functions-runtime/tsdoc-metadata.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-custom-functions-runtime/tsdoc-metadata.json) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-excel-release/tsdoc-metadata.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-excel-release/tsdoc-metadata.json) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-excel/tsdoc-metadata.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-excel/tsdoc-metadata.json) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-office-runtime/tsdoc-metadata.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-office-runtime/tsdoc-metadata.json) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-office/office.d.ts](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-office/office.d.ts) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-office/tsdoc-metadata.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-office/tsdoc-metadata.json) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-onenote/tsdoc-metadata.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-onenote/tsdoc-metadata.json) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_1/tsdoc-metadata.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_1/tsdoc-metadata.json) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_2/tsdoc-metadata.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_2/tsdoc-metadata.json) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_3/tsdoc-metadata.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_3/tsdoc-metadata.json) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_4/tsdoc-metadata.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_4/tsdoc-metadata.json) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_5/tsdoc-metadata.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_5/tsdoc-metadata.json) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_6/tsdoc-metadata.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_6/tsdoc-metadata.json) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_7/tsdoc-metadata.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_7/tsdoc-metadata.json) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-outlook/outlook.d.ts](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-outlook/outlook.d.ts) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-outlook/tsdoc-metadata.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-outlook/tsdoc-metadata.json) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-powerpoint/tsdoc-metadata.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-powerpoint/tsdoc-metadata.json) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-visio/tsdoc-metadata.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-visio/tsdoc-metadata.json) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-word-release/tsdoc-metadata.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-word-release/tsdoc-metadata.json) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-word/tsdoc-metadata.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-word/tsdoc-metadata.json) | :white_check_mark:Succeeded | |
[generate-docs/json/Outlook_1_1.api.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/json/Outlook_1_1.api.json) | :white_check_mark:Succeeded | |
[generate-docs/json/Outlook_1_2.api.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/json/Outlook_1_2.api.json) | :white_check_mark:Succeeded | |
[generate-docs/json/Outlook_1_3.api.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/json/Outlook_1_3.api.json) | :white_check_mark:Succeeded | |
[generate-docs/json/Outlook_1_4.api.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/json/Outlook_1_4.api.json) | :white_check_mark:Succeeded | |
[generate-docs/json/Outlook_1_5.api.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/json/Outlook_1_5.api.json) | :white_check_mark:Succeeded | |
[generate-docs/json/Outlook_1_6.api.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/json/Outlook_1_6.api.json) | :white_check_mark:Succeeded | |
[generate-docs/json/Outlook_1_7.api.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/json/Outlook_1_7.api.json) | :white_check_mark:Succeeded | |
[generate-docs/json/custom-functions-runtime.api.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/json/custom-functions-runtime.api.json) | :white_check_mark:Succeeded | |
[generate-docs/json/excel.api.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/json/excel.api.json) | :white_check_mark:Succeeded | |
[generate-docs/json/excel_release.api.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/json/excel_release.api.json) | :white_check_mark:Succeeded | |
[generate-docs/json/office-runtime.api.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/json/office-runtime.api.json) | :white_check_mark:Succeeded | |
[generate-docs/json/office.api.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/json/office.api.json) | :white_check_mark:Succeeded | |
[generate-docs/json/onenote.api.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/json/onenote.api.json) | :white_check_mark:Succeeded | |

This comment lists only the first 50 files in the pull request.
For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C7%5C17%5C0e1871f2-88cb-c16b-6d81-dc80e4f66cef%5CPullRequest%5C201907171951365834-456%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=mfcGy08%2BRHhEOn2ch%2F9gHBkUdMnTdD8T8kQjjo1A%2B%2Fw%3D&st=2019-07-17T19%3A53%3A03Z&se=2019-08-17T19%3A58%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kbrandl** [comment]
@AlexJerabek yes - if PR #455 is ready for publication, go ahead and merge it into **master** and it'll get included in this PR from **master** to **live**. I'll wait to merge this one until after PR #455 is merged. Thanks!

**Comment by AlexJerabek** [comment]
Thanks @kbrandl. My changes are in and ready to go.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[3c35772](https://github.com/OfficeDev/office-js-docs-reference/pull/456/commits/3c35772ab5e78a51db28f542e42c94eb98cbfa29)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/docs-ref-autogen/custom-functions-runtime/customfunctions.streaminginvocation.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/custom-functions-runtime/customfunctions.streaminginvocation.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/excel.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel.interfaces.functionresultdata.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/excel/excel.interfaces.functionresultdata.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel.worksheet.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/excel/excel.worksheet.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excel.worksheetsingleclickedeventargs.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/excel/excel.worksheetsingleclickedeventargs.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_release.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/excel_release.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel_release/excel.interfaces.functionresultdata.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/excel_release/excel.interfaces.functionresultdata.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/office/office.asyncresult.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/office/office.asyncresult.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/office/office.binding.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/office/office.binding.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/office/office.document.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/office/office.document.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/office/office.ipromiseconstructor.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/office/office.ipromiseconstructor.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/office/office.requirementsetsupport.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/office/office.requirementsetsupport.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/office/officeextension.clientrequestcontext.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/office/officeextension.clientrequestcontext.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/office/officeextension.eventinfo.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/office/officeextension.eventinfo.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/office/officeextension.runoptions.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/office/officeextension.runoptions.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/onenote.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/onenote.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/outlook/office.sharedproperties.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/outlook/office.sharedproperties.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/visio.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/visio.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/word.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/word.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/word_release.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/master/docs/docs-ref-autogen/word_release.yml) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-custom-functions-runtime/tsdoc-metadata.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-custom-functions-runtime/tsdoc-metadata.json) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-excel-release/tsdoc-metadata.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-excel-release/tsdoc-metadata.json) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-excel/tsdoc-metadata.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-excel/tsdoc-metadata.json) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-office-runtime/tsdoc-metadata.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-office-runtime/tsdoc-metadata.json) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-office/office.d.ts](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-office/office.d.ts) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-office/tsdoc-metadata.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-office/tsdoc-metadata.json) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-onenote/tsdoc-metadata.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-onenote/tsdoc-metadata.json) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_1/tsdoc-metadata.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_1/tsdoc-metadata.json) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_2/tsdoc-metadata.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_2/tsdoc-metadata.json) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_3/tsdoc-metadata.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_3/tsdoc-metadata.json) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_4/tsdoc-metadata.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_4/tsdoc-metadata.json) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_5/tsdoc-metadata.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_5/tsdoc-metadata.json) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_6/tsdoc-metadata.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_6/tsdoc-metadata.json) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_7/tsdoc-metadata.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-outlook-legacy/Outlook_1_7/tsdoc-metadata.json) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-outlook/outlook.d.ts](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-outlook/outlook.d.ts) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-outlook/tsdoc-metadata.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-outlook/tsdoc-metadata.json) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-powerpoint/tsdoc-metadata.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-powerpoint/tsdoc-metadata.json) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-visio/tsdoc-metadata.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-visio/tsdoc-metadata.json) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-word-release/tsdoc-metadata.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-word-release/tsdoc-metadata.json) | :white_check_mark:Succeeded | |
[generate-docs/api-extractor-inputs-word/tsdoc-metadata.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/api-extractor-inputs-word/tsdoc-metadata.json) | :white_check_mark:Succeeded | |
[generate-docs/json/Outlook_1_1.api.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/json/Outlook_1_1.api.json) | :white_check_mark:Succeeded | |
[generate-docs/json/Outlook_1_2.api.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/json/Outlook_1_2.api.json) | :white_check_mark:Succeeded | |
[generate-docs/json/Outlook_1_3.api.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/json/Outlook_1_3.api.json) | :white_check_mark:Succeeded | |
[generate-docs/json/Outlook_1_4.api.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/json/Outlook_1_4.api.json) | :white_check_mark:Succeeded | |
[generate-docs/json/Outlook_1_5.api.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/json/Outlook_1_5.api.json) | :white_check_mark:Succeeded | |
[generate-docs/json/Outlook_1_6.api.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/json/Outlook_1_6.api.json) | :white_check_mark:Succeeded | |
[generate-docs/json/Outlook_1_7.api.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/json/Outlook_1_7.api.json) | :white_check_mark:Succeeded | |
[generate-docs/json/custom-functions-runtime.api.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/json/custom-functions-runtime.api.json) | :white_check_mark:Succeeded | |
[generate-docs/json/excel.api.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/json/excel.api.json) | :white_check_mark:Succeeded | |
[generate-docs/json/excel_release.api.json](https://github.com/OfficeDev/office-js-docs-reference/blob/master/generate-docs/json/excel_release.api.json) | :white_check_mark:Succeeded | |

This comment lists only the first 50 files in the pull request.
For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C7%5C17%5C0e1871f2-88cb-c16b-6d81-dc80e4f66cef%5CPullRequest%5C201907172015131019-456%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=PA4Og0drSl130DrOucJj1n8s0C%2B9lPzP%2FEI%2FBSNWkVI%3D&st=2019-07-17T20%3A17%3A35Z&se=2019-08-17T20%3A22%3A35Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
