### PR TITLE
Removing Excel preview APIs from master

### PR DESCRIPTION
**Pull request by AlexJerabek**
Note: this is pulling from DefinitelyTyped/office-js, not DefinitelyTyped/office-js-preview, so a couple descriptions are slightly outdated.

### CODE REVIEW

**Comment by o365devx** [comment]
OPS Build status updates of commit _[b45524b](https://github.com/OfficeDev/office-js-docs-reference/pull/283/commits/b45524bdf088cdc16947ce031b6976c1abe41ee1)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 2 sec(s)_

**Comment by o365devx** [comment]
OPS Build status updates of commit _[b45524b](https://github.com/OfficeDev/office-js-docs-reference/pull/283/commits/b45524bdf088cdc16947ce031b6976c1abe41ee1)_: 

:clock10: **Incremental building**: average incremental building time is _5 min(s) 2 sec(s)_

**Comment by kbrandl** [comment]
@AlexJerabek in addition to updates to the Excel-related .yml output files, I'm also seeing changes to OneNote, Word, and Outlook -related .yml output files in this PR.  Is this expected?

**Comment by AlexJerabek** [comment]
@kbrandl Those all reflect the current office-js d.ts. I suspect some setting (beyond the beta version) was different between the two codegen runs. I looked through and everything seems innocent enough. Ricky, Joe, and I have a separate effort to rerun codegen for all the hosts at both the release and beta levels.

**Pull request merged**
